# Generated by Django 2.1.5 on 2019-04-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_cd', models.CharField(max_length=30)),
                ('d_desc', models.CharField(max_length=50)),
                ('d_min', models.IntegerField()),
                ('d_max', models.IntegerField()),
                ('d_role', models.IntegerField()),
            ],
        ),
    ]
