# Generated by Django 2.1.5 on 2019-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0002_auto_20190413_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='d_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
