# Generated by Django 2.1.5 on 2019-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0003_auto_20190413_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='d_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
