# Generated by Django 2.1.5 on 2019-04-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0004_auto_20190413_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
