# Generated by Django 2.1.5 on 2019-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0008_auto_20190414_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='d_max',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='d_min',
            field=models.CharField(max_length=10),
        ),
    ]
