# Generated by Django 2.1.5 on 2019-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0009_auto_20190414_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_roles',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_cd', models.CharField(max_length=30)),
                ('r_desc', models.CharField(max_length=50)),
                ('r_active', models.CharField(max_length=1)),
                ('r_updt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
