# Generated by Django 2.1.5 on 2019-04-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0010_project_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_roles',
        ),
    ]
