# Generated by Django 2.1.5 on 2019-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0013_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.AutoField(default='1022891', primary_key=True, serialize=False),
        ),
    ]
