# Generated by Django 2.1.5 on 2019-04-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0014_auto_20190419_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
