# Generated by Django 2.1.5 on 2019-04-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0016_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
