# Generated by Django 2.1.5 on 2019-04-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0017_auto_20190420_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_select',
            fields=[
                ('id_desc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_val', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_cl',
            field=models.IntegerField(default=1.5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_el',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_fl',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_sl',
            field=models.IntegerField(default=2),
        ),
    ]
