# Generated by Django 2.1.5 on 2019-04-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0018_auto_20190420_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_desig',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sdate', models.DateField()),
                ('edate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Designation')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_caddr1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_caddr2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_caddr3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_disb',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_prev_cmp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_prev_exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_desig',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee'),
        ),
    ]
