# Generated by Django 2.1.5 on 2019-04-21 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0019_auto_20190421_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_sal',
            fields=[
                ('es_id', models.IntegerField(primary_key=True, serialize=False)),
                ('es_ctc', models.IntegerField()),
                ('es_sdate', models.DateField()),
                ('es_edate', models.DateField(blank=True, null=True)),
                ('es_status', models.CharField(max_length=1)),
                ('es_eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee')),
            ],
        ),
        migrations.RenameField(
            model_name='employee_desig',
            old_name='did',
            new_name='ed_did',
        ),
        migrations.RenameField(
            model_name='employee_desig',
            old_name='edate',
            new_name='ed_edate',
        ),
        migrations.RenameField(
            model_name='employee_desig',
            old_name='eid',
            new_name='ed_eid',
        ),
        migrations.RenameField(
            model_name='employee_desig',
            old_name='id',
            new_name='ed_id',
        ),
        migrations.RenameField(
            model_name='employee_desig',
            old_name='sdate',
            new_name='ed_sdate',
        ),
        migrations.RenameField(
            model_name='employee_desig',
            old_name='status',
            new_name='ed_status',
        ),
    ]
