# Generated by Django 2.1.5 on 2019-04-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0020_auto_20190421_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_desig',
            name='ed_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee_sal',
            name='es_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
