# Generated by Django 2.1.5 on 2019-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0021_auto_20190422_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
