# Generated by Django 2.1.5 on 2019-04-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0022_auto_20190423_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_desig',
            name='ed_did',
        ),
        migrations.RemoveField(
            model_name='employee_desig',
            name='ed_eid',
        ),
        migrations.RemoveField(
            model_name='employee_sal',
            name='es_eid',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employee_desig',
        ),
        migrations.DeleteModel(
            name='Employee_sal',
        ),
    ]
