# Generated by Django 2.1.5 on 2019-04-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0023_auto_20190423_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_fname', models.CharField(max_length=50)),
                ('e_lname', models.CharField(max_length=50)),
                ('e_sname', models.CharField(max_length=50)),
                ('e_dob', models.DateField()),
                ('e_bgroup', models.CharField(max_length=3)),
                ('e_mstatus', models.CharField(max_length=1)),
                ('e_nationality', models.CharField(max_length=50)),
                ('e_disb', models.CharField(blank=True, max_length=1, null=True)),
                ('e_gender', models.CharField(max_length=1)),
                ('e_paddr1', models.CharField(max_length=50)),
                ('e_paddr2', models.CharField(max_length=50)),
                ('e_paddr3', models.CharField(max_length=50)),
                ('e_caddr1', models.CharField(blank=True, max_length=50, null=True)),
                ('e_caddr2', models.CharField(blank=True, max_length=50, null=True)),
                ('e_caddr3', models.CharField(blank=True, max_length=50, null=True)),
                ('e_email', models.CharField(max_length=100)),
                ('e_mnumber', models.IntegerField()),
                ('e_doj', models.DateField(blank=True, null=True)),
                ('e_qfn', models.CharField(max_length=50)),
                ('e_prev_exp', models.IntegerField(blank=True, null=True)),
                ('e_prev_cmp', models.CharField(blank=True, max_length=50, null=True)),
                ('e_cl', models.FloatField(default=1.5)),
                ('e_sl', models.FloatField(default=2)),
                ('e_el', models.FloatField(default=4)),
                ('e_fl', models.FloatField(default=2)),
                ('e_status', models.CharField(max_length=1)),
                ('e_pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_desig',
            fields=[
                ('ed_id', models.AutoField(primary_key=True, serialize=False)),
                ('ed_sdate', models.DateField()),
                ('ed_edate', models.DateField(blank=True, null=True)),
                ('ed_status', models.CharField(max_length=1)),
                ('ed_did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Designation')),
                ('ed_eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_sal',
            fields=[
                ('es_id', models.AutoField(primary_key=True, serialize=False)),
                ('es_ctc', models.FloatField()),
                ('es_sdate', models.DateField()),
                ('es_edate', models.DateField(blank=True, null=True)),
                ('es_status', models.CharField(max_length=1)),
                ('es_eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee')),
            ],
        ),
    ]
