# Generated by Django 2.1.5 on 2019-04-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0025_auto_20190423_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=50)),
                ('pdesc', models.CharField(blank=True, max_length=100, null=True)),
                ('psdate', models.DateField(blank=True, null=True)),
                ('pexpedate', models.DateField(blank=True, null=True)),
                ('pedate', models.DateField()),
                ('pcrtd', models.CharField(blank=True, max_length=50, null=True)),
                ('pclient', models.CharField(blank=True, max_length=100, null=True)),
                ('pstatus', models.CharField(max_length=1)),
                ('powner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee')),
            ],
        ),
    ]
