# Generated by Django 2.1.5 on 2019-05-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0028_auto_20190426_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tdate', models.DateTimeField(blank=True, null=True)),
                ('thours', models.FloatField(blank=True, null=True)),
                ('tstate', models.CharField(max_length=1)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee')),
            ],
        ),
    ]
