# Generated by Django 2.1.5 on 2019-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0031_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='ltype',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
