# Generated by Django 2.1.5 on 2019-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0033_auto_20190508_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pbudget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pcloc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pcomplexity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ptype',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
