# Generated by Django 2.1.5 on 2019-05-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0035_salarymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('edate', models.DateField(blank=True, null=True)),
                ('ctc', models.FloatField(blank=True, null=True)),
                ('ctc_pm', models.FloatField(blank=True, null=True)),
                ('bs', models.FloatField(blank=True, null=True)),
                ('conv', models.FloatField(blank=True, null=True)),
                ('hra', models.FloatField(blank=True, null=True)),
                ('city', models.FloatField(blank=True, null=True)),
                ('sundry', models.FloatField(blank=True, null=True)),
                ('ptax', models.FloatField(blank=True, null=True)),
                ('pf', models.FloatField(blank=True, null=True)),
                ('esis', models.FloatField(blank=True, null=True)),
                ('lop', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee')),
            ],
        ),
    ]
