# Generated by Django 2.1.5 on 2019-05-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0037_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_img',
            field=models.ImageField(default='img/employee/user.png', upload_to='img/employee/'),
        ),
    ]
