# Generated by Django 2.1.5 on 2019-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0038_employee_e_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hdate', models.DateField(blank=True, null=True)),
                ('hdesc', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
