# Generated by Django 2.1.5 on 2019-06-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimatix', '0039_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('appraiseeid', models.CharField(blank=True, max_length=150, null=True)),
                ('asdate', models.DateField(blank=True, null=True)),
                ('aedate', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('updtby', models.CharField(blank=True, max_length=150, null=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultimatix.Employee')),
            ],
        ),
    ]
